#!/bin/sh
TITLE=`mpc | head -n 1`
if [ `mpc | wc -l` == 1 ]
then echo ''
else
    if [ `mpc | grep -o '\[[a-z]\+\]'` == '[playing]' ]
    then echo "<fc=#cc6666></fc> $TITLE"
    else echo "<fc=#f0c674></fc> $TITLE"
    fi
 
fi
