#!/bin/sh

cntPrim=`mu find flag:unread m:/Primary/INBOX | wc -l`
cntWork=`mu find flag:unread m:/Olin/INBOX | wc -l`
cntBab=`mu find flag:unread m:/Babson/Inbox | wc -l`

echo "<fc=#8abeb7></fc> $cntPrim <fc=#969896></fc> $cntWork <fc=#c5c8c6></fc> $cntBab"
